#!/usr/bin/env python3
"""Generate include/type_colors.h from the type icons in romfs.

The colours are sampled from the game's own icons rather than taken from a
fan-site palette, which is a different set entirely: in-game Fighting is orange
and Ground is brown, where the community palette has red and sand. Each icon is
a white glyph on a solid square, so the most common opaque non-white pixel is
that square's colour.

Nothing consumes this today -- the card draws the icons themselves, which need
no colour table. It exists for anything that wants a type colour without an
icon, such as small markers in the box grid.

Usage: python3 tools/gen_type_colors.py
"""
import os
import re
import sys
from collections import Counter

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: pip install Pillow")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICONS = os.path.join(ROOT, "romfs/types")
TARGET = os.path.join(ROOT, "include/type_colors.h")

NAMES = ["Normal", "Fighting", "Flying", "Poison", "Ground", "Rock",
         "Bug", "Ghost", "Steel", "Fire", "Water", "Grass",
         "Electric", "Psychic", "Ice", "Dragon", "Dark", "Fairy"]


def disc_colour(path):
    im = Image.open(path).convert("RGBA")
    counts = Counter()
    for r, g, b, a in im.get_flattened_data() if hasattr(im, "get_flattened_data") else list(im.getdata()):
        if a < 200:
            continue                      # transparent margin
        if r > 235 and g > 235 and b > 235:
            continue                      # the white glyph
        counts[(r, g, b)] += 1
    if not counts:
        sys.exit("no disc colour found in %s" % path)
    return counts.most_common(1)[0][0]


def main():
    colours = []
    for i, name in enumerate(NAMES):
        path = os.path.join(ICONS, "type_icon_s_%02d.png" % i)
        if not os.path.exists(path):
            sys.exit("missing %s" % path)
        colours.append((name, disc_colour(path)))

    lines = ["#pragma once",
             "#include <cstdint>",
             "",
             "// Auto-generated by tools/gen_type_colors.py from romfs/types/.",
             "// The games' own palette, sampled from the type icons themselves.",
             "// Indexed by the modern type IDs used in move_types.h.",
             "",
             "struct TypeColor { uint8_t r, g, b; };",
             "",
             "static constexpr TypeColor TYPE_COLORS[18] = {"]
    for i in range(0, 18, 3):
        row = " ".join("{%3d, %3d, %3d}," % c for _, c in colours[i:i + 3])
        names = ", ".join(n for n, _ in colours[i:i + 3])
        lines.append("    " + row + "  // " + names)
    lines.append("};")
    open(TARGET, "w", encoding="utf-8").write("\n".join(lines) + "\n")

    print("wrote %d type colours into %s" % (len(colours), os.path.relpath(TARGET, ROOT)))
    for name, c in colours:
        print("  %-9s #%02x%02x%02x" % (name, *c))


if __name__ == "__main__":
    main()
