#!/usr/bin/env python3
"""Generate include/species_types.h from the PKHeX personal binaries.

Every personal format stores Type1 at 0x06 and Type2 at 0x07 of its entry.
PKHeX normalises its personal binaries to the modern (Gen6+) type numbering,
including the Gen 3 tables, so the bytes are used as-is (see move_types.h).

Usage: python3 tools/gen_species_types.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PERSONAL = os.path.join(ROOT, "external/PKHeX.Core/Resources/byte/personal")
OUT = os.path.join(ROOT, "include/species_types.h")

# name, binary, entry size, expected count, personal namespace ("" = gen3, indexed
# by internal species id), unused
FAMILIES = [
    ("SV",   "personal_sv",   0x50, 1424, "PersonalSV",   False),
    ("ZA",   "personal_za",   0x50, 1445, "PersonalZA",   False),
    ("SWSH", "personal_swsh", 0xB0, 1192, "PersonalSWSH", False),
    ("LA",   "personal_la",   0xB0, 1276, "PersonalLA",   False),
    ("BDSP", "personal_bdsp", 0x44,  560, "PersonalBDSP", False),
    ("GG",   "personal_gg",   0x54,  980, "PersonalGG",   False),
    ("FRLG", "personal_fr",   0x1C,  387, "",             False),
]


def extract(binary, size, count, gen3):
    path = os.path.join(PERSONAL, binary)
    with open(path, "rb") as f:
        data = f.read()
    if len(data) != size * count:
        sys.exit("%s: expected %d bytes (%d x 0x%X), got %d"
                 % (binary, size * count, count, size, len(data)))
    out = []
    for i in range(count):
        out.append((data[i * size + 6], data[i * size + 7]))
    return out


def emit_array(name, pairs):
    lines = ["static constexpr Pair %s[%d] = {" % (name, len(pairs))]
    for i in range(0, len(pairs), 8):
        chunk = pairs[i:i + 8]
        lines.append("    " + " ".join("{%3d,%3d}," % p for p in chunk))
    lines.append("};")
    return "\n".join(lines)


def main():
    tables = {n: extract(b, s, c, g3) for n, b, s, c, _, g3 in FAMILIES}

    parts = ["""#pragma once
#include <cstdint>
#include "game_type.h"
#include "species_converter.h"
#include "personal_sv.h"
#include "personal_za.h"
#include "personal_swsh.h"
#include "personal_la.h"
#include "personal_bdsp.h"
#include "personal_gg.h"

// Auto-generated by tools/gen_species_types.py from the PKHeX personal binaries.
// Type IDs use the modern (Gen6+) numbering shared with move_types.h:
// 0=Normal, 1=Fighting, ... 16=Dark, 17=Fairy. NONE (0xFF) means no type.

namespace SpeciesTypes {

struct Pair { uint8_t t1, t2; };

static constexpr uint8_t NONE = 0xFF;
"""]

    for name, _, _, _, _, _ in FAMILIES:
        parts.append(emit_array(name, tables[name]))
        parts.append("")

    parts.append("""// Primary/secondary type for a species+form in a given game.
// t2 is NONE when the species is single-typed.
inline Pair get(GameType g, uint16_t natdex, uint8_t form) {
    Pair p{NONE, NONE};
    if (natdex == 0) return p;

    if (isFRLG(g)) {
        uint16_t internal = SpeciesConverter::getInternal3(natdex);
        if (internal < 387) p = FRLG[internal];
    } else if (isSV(g)) {
        p = SV[PersonalSV::getEntryIndex(natdex, form)];
    } else if (g == GameType::ZA) {
        p = ZA[PersonalZA::getEntryIndex(natdex, form)];
    } else if (isSwSh(g)) {
        p = SWSH[PersonalSWSH::getEntryIndex(natdex, form)];
    } else if (g == GameType::LA) {
        p = LA[PersonalLA::getEntryIndex(natdex, form)];
    } else if (isBDSP(g)) {
        p = BDSP[PersonalBDSP::getEntryIndex(natdex, form)];
    } else if (isLGPE(g)) {
        p = GG[PersonalGG::getEntryIndex(natdex, form)];
    }

    if (p.t2 == p.t1) p.t2 = NONE;  // PKHeX stores single types twice
    return p;
}

} // namespace SpeciesTypes""")

    with open(OUT, "w") as f:
        f.write("\n".join(parts) + "\n")
    print("wrote %s" % OUT)
    for name, _, _, _, _, _ in FAMILIES:
        print("  %-5s %4d entries" % (name, len(tables[name])))


if __name__ == "__main__":
    main()
